CREATE TABLE customer (
    id SERIAL PRIMARY KEY,
    name VARCHAR(60) NOT NULL,
    cpf CHAR(11) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)